export const codeEnArr = [
 'thunderstorm with light rain',
 'thunderstorm with rain',
 'thunderstorm with heavy rain',
 'light thunderstorm',
 'thunderstorm',
 'heavy thunderstorm',
 'ragged thunderstorm',
 'thunderstorm with light drizzle',
 'thunderstorm with drizzle',
 'thunderstorm with heavy drizzle',
 'light intensity drizzle',
 'drizzle',
 'heavy intensity drizzle',
 'light intensity drizzle rain',
 'drizzle rain',
 'heavy intensity drizzle rain',
 'shower rain and drizzle',
 'heavy shower rain and drizzle',
 'shower drizzle',
 'light rain',
 'moderate rain',
 'heavy intensity rain',
 'very heavy rain',
 'extreme rain',
 'freezing rain',
 'light intensity shower rain',
 'shower rain',
 'heavy intensity shower rain',
 'ragged shower rain',
 'light snow',
 'Snow',
 'Heavy snow',
 'Sleet',
 'Light shower sleet',
 'Shower sleet',
 'Light rain and snow',
 'Rain and snow',
 'Light shower snow',
 'Shower snow',
 'Heavy shower snow',
 'mist',
 'Smoke',
 'Haze',
 'sand/ dust whirls',
 'fog',
 'sand',
 'dust',
 'volcanic ash',
 'squalls',
 'tornado',
 'clear sky',
 'few clouds',
 'few clouds: 11-25%',
 'scattered clouds',
 'broken clouds',
 'overcast clouds',
]
export const codeKrArr = [
  '약한 비를 동반한 뇌우',
  '비를 동반한 뇌우',
  '폭우를 동반한 뇌우',
  '가벼운 뇌우',
  '뇌우',
  '강한 뇌우',
  '거친 뇌우',
  '약한 이슬비를 동반한 뇌우',
  '이슬비를 동반한 뇌우',
  '강한 이슬비를 동반한 뇌우',
  '약한 이슬비',
  '이슬비',
  '강한 이슬비',
  '약한 이슬비',
  '이슬비',
  '강한 강도의 이슬비',
  '소나기 비와 이슬비',
  '강한 소나기 비와 이슬비',
  '이슬비',
  '약한비',
  '비내림',
  '강한 강도의 비',
  '매우 큰 비',
  '극심한 비',
  '우박 섞인 비',
  '약한 소나기',
  '소나기',
  '강한 강도의 소나기',
  '굵은 소나기',
  '가벼운 눈',
  '눈',
  '폭설',
  '진눈깨비',
  '가벼운 샤워 진눈깨비',
  '진눈깨비',
  '가벼운 비와 눈',
  '비와 눈',
  '가벼운 소나기 눈',
  '소나기 눈',
  '폭설',
  '얕은 안개',
  '매연',
  '연한 안개',
  '모래, 먼지 소용돌이',
  '안개',
  '모래',
  '먼지',
  '화산재',
  '돌풍',
  '폭풍',
  '맑은 하늘',
  '연한 구름',
  '약간의 구름',
  '구름',
  '많은 구름',
  '진한 구름',
 ]
